name: Windows Cloud RDP

on:
  workflow_dispatch:
    inputs:
      apps:
        description: "WinGet App IDs separated by commas"
        required: false
        default: ""
        type: string

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    env:
      RDP_USER: Arash110
      RDP_PORT: "3389"
      TAILSCALE_HOSTNAME: github-rdp-${{ github.run_id }}

    steps:

      - name: 1. Enable Remote Desktop
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"

          Set-ItemProperty `
            -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
            -Name 'fDenyTSConnections' `
            -Value 0 `
            -Force

          Set-ItemProperty `
            -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
            -Name 'UserAuthentication' `
            -Value 1 `
            -Force

          # Ensure the Remote Desktop service is running
          Set-Service -Name TermService -StartupType Automatic -ErrorAction Stop
          Start-Service -Name TermService -ErrorAction SilentlyContinue
          Restart-Service -Name TermService -Force -ErrorAction SilentlyContinue

          Disable-NetFirewallRule `
            -DisplayGroup 'Remote Desktop' `
            -ErrorAction SilentlyContinue

          Write-Host 'Remote Desktop enabled with NLA.'


      - name: 2. Create RDP Administrator Account
        shell: powershell
        env:
          RDP_PASSWORD: ${{ secrets.RDP_
